ALTER TABLE flashcard_sets 
  ADD COLUMN visibility VARCHAR(10) NOT NULL DEFAULT 'PRIVATE',
  ADD COLUMN share_code VARCHAR(20) NULL UNIQUE,
  ADD COLUMN allow_copy BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN allow_review BOOLEAN NOT NULL DEFAULT TRUE;
